### ISSUE TITLE
Code review from command line

### ISSUE THREAD

**Issue by albfan** [janestreet/iron#5]
After look at https://blog.janestreet.com/putting-the-i-back-in-ide-towards-a-github-explorer/

![screencast](https://blog.janestreet.com/putting-the-i-back-in-ide-towards-a-github-explorer/review-patch.png)

wonder if that cli is avaliable.

I'm part of GNOME foundation where we recently we migrated to gitlab 

https://gitlab.gnome.org/GNOME/

We get an improvement from gitlab visual cool code review:

https://gitlab.gnome.org/GNOME/gnome-builder/merge_requests/49

but as me, many ones are terminal hackers, and review code from command line would be great

Is it possible to point out the code or help to release some open source part of it?

**Comment by dwang20151005** [comment]
We've had a few people try to run this code outside our walls, and the conclusion has been that it's not worth the trouble.  You're better off learning about the system at a higher level and re-implementing the useful bits from scratch.

We actually meant to stop releasing the code (you can read the new README for the reasoning), and it was a mistake that we had this code available for a few days.  We've now un-released the code.

If you have any questions toward re-implementing iron, we're happy to discuss.

**Comment by avsm** [comment]
@albfan We have been considering working with Jane Street to build an open-source version of Iron that is suitable for a distributed Git/Hub|Lab workflow, but its still in the early planning phases. If GNOME is also interested, we should talk in the next few months to compare notes... 

/cc @yminsky @samoht

**Comment by albfan** [comment]
@avsm count on me to push on it, will ask on IRC and see what people think. I'm even not sure about the API for git providers (for code review)

Are you under any org? Just to know if somebody ask

**Comment by yminsky** [comment]
And we're not averse to releasing parts of Iron. One obvious tool that could be shared (and could benefit from some contributions!) is patdiff and patdiff4, which are the tools for visualizing simple diffs and diffs-through-a-rebase. And there might be some other core bits that would benefit from sharing, like the core data types for modeling what a reviewer knows (known as a "reviewer brain", in Iron parlance.)

**Comment by albfan** [comment]
@yminsky As many other "game changer", one thing that could help to spread out a new concept is to let people play with it (as users or hackint on it).

So if release some bits can help to standardize your workflow (so maybe the learning curve for developers inside janestreet gets lowered) I commit you to do it, just to see what happens.

Community can add perspective and valuable feedback.
